## Listas, strings, vetores e matrizes

Tuplas e listas são variáveis compostas, isto é, estruturas de dados em Python muito úteis para
armazenar uma coletânea de objetos de forma indexada, ou seja, em cada posição da lista ou da
tupla temos uma variável. A figura a seguir ilustra essa ideia como um trem de dados.

<img src= compostas.png>

### O trem de dados my_array é uma única variável

A única diferença entre uma tupla e uma lista, é que tuplas são objetos imutáveis, ou seja, uma vez
criados não podem ser modificados. Em outras palavras, é impossível usar o operador de atribuição
com uma tupla. As listas por outro lado podem ser modificadas sempre que necessário e portanto
são muito mais utilizadas na prática do que as tuplas.

In [1]:
# criar uma lista vazia
lista = []

In [2]:
lista

[]

In [3]:
# criar uma lista com 3 notas

notas = [7.5, 9, 8.3]
notas

[7.5, 9, 8.3]

In [4]:
notas[0] = 9.3
notas

[9.3, 9, 8.3]

In [5]:
# lista com 5 elementos

la = [1,2,3,4,5]
print("A lista 'la' contém %d elementos" %len(la))

A lista 'la' contém 5 elementos


In [6]:
# random

import random

lb = []
for i in range(5):
    lb.append(random.randint(0,1000))
    
print("A lista 'lc' contém %d elementos aleatórios" %len(lb))
print(lb)

A lista 'lc' contém 5 elementos aleatórios
[750, 554, 38, 578, 489]


In [7]:
# concatenando listas

lc = la + lb
lc

[1, 2, 3, 4, 5, 750, 554, 38, 578, 489]

In [8]:
type(lc)

list

In [9]:
lc.append(101)

In [10]:
lc

[1, 2, 3, 4, 5, 750, 554, 38, 578, 489, 101]

In [11]:
print("A lista 'lc' contém %d elementos aleatórios" %len(lc))

A lista 'lc' contém 11 elementos aleatórios


In [12]:
# encontrarndo maior e menor elemento da lista

print("Maior elemento de lc é %d" %max(lc))
print("Menor elemento de lc é %d" %min(lc))

Maior elemento de lc é 750
Menor elemento de lc é 1


In [13]:
# ordenando a lista

print("Lista 'lc' ordenada: ")
lc.sort()
print(lc)

Lista 'lc' ordenada: 
[1, 2, 3, 4, 5, 38, 101, 489, 554, 578, 750]


In [17]:
# apresentar 5 valores inteiros

vetor = []
i = 1
while i <= 5:
    n = int(input("Entre com o valor: "))
    vetor.append(n)
    i+=1

print("Vetor lido: ",vetor)

Entre com o valor: 5
Entre com o valor: 8
Entre com o valor: 3
Entre com o valor: 7
Entre com o valor: 1
Vetor lido:  [5, 8, 3, 7, 1]


In [21]:
# valores descritivos

notas = []
soma = 0
i = 1
while i <= 4:
    n = float(input("Entre com a nota: "))
    notas.append(n)
    soma+=n
    i+=1
    
print("Notas: ", notas)
print("O valor da média é:  %.2f" %(soma/4))

estado = soma/4
if estado < 4:
    print("Que pena, você está reprovado")
elif estado <= 5:
    print("Cuidado, você está de exame")
else:
    print("Parabéns, você está aprovado")

Entre com a nota: 3
Entre com a nota: 6
Entre com a nota: 2
Entre com a nota: 8
Notas:  [3.0, 6.0, 2.0, 8.0]
O valor da média é:  4.75
Cuidado, você está de exame


## Slicing (fatiamento)

In [25]:
l = [9,8,7,6,5,4,3,2,1]
l[4:6]

[5, 4]

## List Comprehensions

In [26]:
# sequencia de caracteres

lst = [x for x in 'aulasPython']
lst

['a', 'u', 'l', 'a', 's', 'P', 'y', 't', 'h', 'o', 'n']

In [27]:
# Variável elevada ao quadrado para um range

lst = [x**2 for x in range(0,11)]
lst

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [31]:
# Lista antiga

l

[9, 8, 7, 6, 5, 4, 3, 2, 1]

In [38]:
# números impares

ls = [x for x in l if x%2 == 1]
ls

[9, 7, 5, 3, 1]

In [34]:
# valores pares

ls3 = [x for x in l if x%2 == 0]
ls3

[8, 6, 4, 2]

In [39]:
l4 = [x**2 for x in l if x%2 == 0]
l4

[64, 36, 16, 4]

In [40]:
celsius = [0,10,20.1,34.5]
fahr = [e * 9/5 + 32 for e in celsius]
fahr

[32.0, 50.0, 68.18, 94.1]

In [41]:
# filtro de listas

a = [-4, 2, 0, -1, 12, -3]
b = [e for e in a if e > 0]
b

[2, 12]

In [42]:
# filtrando tipos de variáveis

a = ['a', 2, 'c', 12, 'd', 4.7, 'aulas']

b = [e for e in a if type(e) == int]
c = [e for e in a if type(e) == str]
d = [e for e in a if type(e) == float]

print("Lista original:", a)
print("Valores inteiros: ", b)
print("Valores strings: ", c)
print("Valores float: ", d)

Lista original: ['a', 2, 'c', 12, 'd', 4.7, 'aulas']
Valores inteiros:  [2, 12]
Valores strings:  ['a', 'c', 'd', 'aulas']
Valores float:  [4.7]


In [43]:
# encontrando vogais

def vogal(c):
    v = 'aeiou'
    if c in v:
        return True
    else:
        return False


In [45]:
frase = "estou estudando python no Hubia"

vogais = [c for c in frase if vogal(c)]
vogais

['e', 'o', 'u', 'e', 'u', 'a', 'o', 'o', 'o', 'u', 'i', 'a']

In [47]:
# Condição no início

transform = ["par" if i %2 == 0 else "impar" for i in range(10)]
print(transform)

['par', 'impar', 'par', 'impar', 'par', 'impar', 'par', 'impar', 'par', 'impar']


In [48]:
# utilizando multiplas condições

a = [9, 2, 18, 14, 22, 11, 7, 19, 23]
b = [e for e in a if e > 10 if e < 20]
b

[18, 14, 11, 19]

In [50]:
# loops aninhados (produto cartesiano de duas listas)

a = [1,2,3,4,5]
b = ['a','b','c','d','e']

c = [str(i) + j for i in a for j in b]
print(c)

['1a', '1b', '1c', '1d', '1e', '2a', '2b', '2c', '2d', '2e', '3a', '3b', '3c', '3d', '3e', '4a', '4b', '4c', '4d', '4e', '5a', '5b', '5c', '5d', '5e']


In [51]:
# nivelando listas

num1 = [[1,2,3],[4,5,6],[7,8,9]]
c = [l for num in num1 for l in num]
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [52]:
num1 = [[1,2,3],
        [4,5,6],
        [7,8,9]]
m1 = [[row[i] for row in num1] for i in range(3)]
m1

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]

## Expressões Lambda

Expressões lambda são chamadas de funções anônimas, nada mais são do que funções que o usuário não precisa definir, ou seja, não vai precisar escrever a função e depois utilizá-la dentro do código

In [63]:
# somando argumentos

x = lambda a:a+10
x(5)

15

In [64]:
# multiplicando por b

x = lambda a, b: a*b
print(x(5,6))

30


In [65]:
(lambda a, b: a*b)(3,4)

12

In [66]:
(lambda x, y, z: x + y + z)(2, 4, 8)

14

In [68]:
# lambda também recebe parâmetros de nomes

full_name = lambda primeiro, ultimo: f'nome completo: {primeiro.title()}{ultimo.title()}'
full_name('Clayton',' Pereira')

'nome completo: Clayton Pereira'

## Função Map

Pega uma lista de informações e aplica sobre cada um dos valores dessa lista de informações, uma função.
Então, sempre que for executar uma função para vários valores de uma lista, nós vamos urilizar a função **map**.

In [69]:
# Alterando a fonte

list(map(lambda x: x.upper(), ['gato','cachorro', 'camelo', 'elefante']))

['GATO', 'CACHORRO', 'CAMELO', 'ELEFANTE']

In [70]:
# com list comprehension

[x.capitalize() for x in ['gato','cachorro', 'camelo', 'elefante']]

['Gato', 'Cachorro', 'Camelo', 'Elefante']

In [73]:
# filtrando por vogais

list(filter(lambda x: 'ga' in x, ['gato','cachorro', 'camelo', 'elefante']))

1

In [75]:
# calculo de imposto com 30%

preco = 1000

def calc_imposto(preco):
    return preco*0.3

In [78]:
calc_imposto(preco)

300.0

In [77]:
calc_imposto2 = lambda x: x*0.3
calc_imposto2(preco)

300.0

In [79]:
# Map em cada valor da lista

precos = [1000, 3000, 5000, 10000]
impostos = list(map(lambda x: x*0.3, precos))
impostos

[300.0, 900.0, 1500.0, 3000.0]

In [80]:
# criando o objeto map

preco2_imp = map(calc_imposto, precos)
print(preco2_imp)

In [82]:
# apresentando o resultado com o list

preco2_imp = list(map(calc_imposto, precos))
print(preco2_imp)

[300.0, 900.0, 1500.0, 3000.0]


In [83]:
# retorna o produto de todos os elementos da lista

from functools import reduce

lista = [1,2,3,4,5,6]
produto = reduce(lambda x,y: x*y, lista)
print("lista = ", lista, "\n\nproduto = ", produto)

lista =  [1, 2, 3, 4, 5, 6] 

produto =  720


In [91]:
# resultado em um for do lambda

all_list = [lambda arg=x: arg * 10 for x in range(1,5)]
for i in all_list:
    print(i())

10
20
30
40


In [92]:
# filtrando mioridade

idade = [13, 90, 17, 21, 60, 32]
adultos = list(filter(lambda age: age > 18, idade))
print(adultos)

[90, 21, 60, 32]


In [93]:
import numpy as np

In [97]:
a = np.array([[2, 4, 6, 8, 10],[1,3,5,7,9]])
np.shape(a)

(2, 5)

In [99]:
a.dtype

dtype('int64')

In [100]:
len(a)

2

In [101]:
b = (2, 4)
type(b)

tuple

In [102]:
b[0]

2

In [109]:
b = np.full((3,2),5)
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [107]:
b[0] = 2
b

array([[2., 2.],
       [0., 0.],
       [0., 0.]])

In [110]:
b.T

array([[5, 5, 5],
       [5, 5, 5]])

In [111]:
b

array([[5, 5],
       [5, 5],
       [5, 5]])

In [116]:
b.sum(axis=0)

array([15, 15])

In [114]:
b.sum(axis=1)

array([10, 10, 10])